using System;
using System.Collections.Generic;

namespace SaudiEinvoiceService.Models
{
    public partial class Mat
    {
        public Guid Guid { get; set; }
        public int Number { get; set; }
        public string? Code { get; set; }
        public string? Name { get; set; }
        public string? LatinName { get; set; }
        public int? Kind { get; set; }
        public string? Description { get; set; }
        public string? Barcode { get; set; }
        public string? Model { get; set; }
        public double? FirstCostPrice { get; set; }
        public double? CostPrice { get; set; }
        public double? TransPrice { get; set; }
        public int? CalcWay { get; set; }
        public string? Unit1 { get; set; }
        public double? Unit1Sell { get; set; }
        public double? Unit1LessSell { get; set; }
        public string? Location { get; set; }
        public double? FirstBalance { get; set; }
        public double? Balance { get; set; }
        public int? GroupNumber { get; set; }
        public int? MatEqualNumber { get; set; }
        public Guid? GroupGuid { get; set; }
        public Guid? MatEqualGuid { get; set; }
        public int? DefUnit { get; set; }
        public double? MaxQty { get; set; }
        public double? MinQty { get; set; }
        public double? ReorderQty { get; set; }
        public Guid? AccGuid { get; set; }
        public string? Fld1 { get; set; }
        public string? Fld2 { get; set; }
        public string? Fld3 { get; set; }
        public string? Fld4 { get; set; }
        public string? Fld5 { get; set; }
        public string? Fld6 { get; set; }
        public bool? Serial { get; set; }
        public bool? WithDesc { get; set; }
        public double? LastBuyPrice { get; set; }
        public double? LessBuyPrice { get; set; }
        public int? ViewWay { get; set; }
        public Guid? PictureGuid { get; set; }
        public int? Flag { get; set; }
        public string? CustName { get; set; }
        public string? Phone { get; set; }
        public string? Fax { get; set; }
        public string? Address { get; set; }
        public double? BuyDiscRate { get; set; }
        public double? BuyDiscVal { get; set; }
        public double? SaleDiscRate { get; set; }
        public double? SaleDiscVal { get; set; }
        public int? DiscAffectCost { get; set; }
        public int? Branch { get; set; }
        public Guid? CostAccGuid { get; set; }
        public Guid? StkAccGuid { get; set; }
        public int? WarrPeriod { get; set; }
        public string? WarrType { get; set; }
        public double? CashComm { get; set; }
        public double? LaterComm { get; set; }
        public int? CommType { get; set; }
        public string? Producer { get; set; }
        public int? BuyDiscType { get; set; }
        public int? SaleDiscType { get; set; }
        public double? BuyFqrate { get; set; }
        public double? SaleFqrate { get; set; }
        public double? CustomerPrice { get; set; }
        public Guid? PurAccGuid { get; set; }
        public Guid? ReSaleAccGuid { get; set; }
        public Guid? RePurAccGuid { get; set; }
        public double? DefQty { get; set; }
        public bool? BuyFreeQtyIsInteger { get; set; }
        public bool? SaleFreeQtyIsInteger { get; set; }
        public double? Cnt { get; set; }
        public Guid? AssetGroupGuid { get; set; }
        public string? InUnit { get; set; }
        public double? LengthRate { get; set; }
        public double? WidthRate { get; set; }
        public double? HeightRate { get; set; }
        public double? MaxBuyDiscRate { get; set; }
        public double? MaxBuyDiscVal { get; set; }
        public double? MaxSaleDiscRate { get; set; }
        public double? MaxSaleDiscVal { get; set; }
        public double? DefAge { get; set; }
        public int? DefAgeType { get; set; }
        public bool? Taxable { get; set; }
        public double? AddTaxRate { get; set; }
        public Guid? AddTaxSaleAccGuid { get; set; }
        public Guid? AddTaxPurAccGuid { get; set; }
        public double? FunTaxRate { get; set; }
        public Guid? FunTaxSaleAccGuid { get; set; }
        public Guid? FunTaxPurAccGuid { get; set; }
        public double? CalcFirstCostPrice { get; set; }
        public bool? IsBatchNo { get; set; }
        public int? TaxableType { get; set; }
        public double? Num1 { get; set; }
        public double? Num2 { get; set; }
        public DateTime? ActDate { get; set; }
        public Guid? StoreGuid { get; set; }
        public bool? WithDefinition { get; set; }
        public int? Color { get; set; }
        public string? Gs1code { get; set; }
        public string? Egscode { get; set; }
        public string? Gpccode { get; set; }
        public bool? IntegerQty { get; set; }
        public double? Weight { get; set; }
        public bool? OneDefinitionInOper { get; set; }
        public string? ZidId { get; set; }
        public string? Gtin { get; set; }
        public bool? ShowInExternal { get; set; }
    }
}
